name: Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Rust 1.76.0
        run: |
          rustup install 1.76.0-x86_64-unknown-linux-gnu
          rustup default 1.76.0-x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release

      - name: Get version
        run: echo "CARGO_VERSION=$(grep '^version = ' Cargo.toml | cut -d '"' -f2)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.CARGO_VERSION }}-custom
          tag_name: v${{ env.CARGO_VERSION }}-custom
          files: target/release/libdrift_ffi_sys.so
          generate_release_notes: false
          body: "Custom build for Tail Trade (program ID: 2XUSofeGHdvDTFsV2y9JCREKjy4PB3BtaXve5ZPiU66a)"
